# Generated by Django 4.1.3 on 2022-11-15 02:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room", old_name="created_at", new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="room", old_name="guest_can_pause", new_name="guestCanPause",
        ),
        migrations.RenameField(
            model_name="room", old_name="votes_to_skip", new_name="votesToSkip",
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
    ]
